---

- name: Ensure JIRA group
  group:
    name: "{{ jira_group }}"

- name: Ensure JIRA user
  user:
    name: "{{ jira_user }}"
    group: "{{ jira_group }}"
    shell: /bin/bash

- name: Create path for JIRA's folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
  with_items:
    - "{{ jira_home }}"
    - "{{ jira_download_dir }}"
    - "{{ jira_installation_dir }}"

- name: Link attachments folder in case not using default one
  file:
    src: "{{ jira_home }}/data/attachments"
    dest: "{{ jira_attachments_dir }}"
    state: link
  when: jira_attachments_dir != "{{ jira_home }}/data/attachments"

- name: Download package
  get_url:
    dest: "{{ jira_download_dir }}/{{ jira_package }}"
    url: "{{ jira_installation_url }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
  register: jira_downloaded

- name: Unarchive package
  unarchive:
    src: "{{ jira_download_dir }}/{{ jira_package }}"
    dest: "{{ jira_installation_dir }}"
    remote_src: yes
    extra_opts: --strip-components=1
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
  when: jira_downloaded.changed
  tags:
    - skip_ansible_lint

- name: Make sure specified directories exist for data center setup
  file:
    path: "{{ item }}"
    owner: "{{ jira_user }}"
    group: "{{ jira_group }}"
    mode: 0755
    state: directory
    recurse: yes
  with_items:
    - "{{ jira_datacenter_shared_home }}"
    - "{{ jira_home }}/data"
    - "{{ jira_home }}/plugins"
    - "{{ jira_home }}/logos"
    - "{{ jira_home }}/import"
    - "{{ jira_home }}/export"
    - "{{ jira_home }}/caches"
  when: jira_install_datacenter

- name: Copying directories to shared home for data center setup
  copy:
    src: "{{ item }}"
    dest: "{{ jira_datacenter_shared_home }}/"
    owner: "{{ jira_user }}"
    remote_src: true
  with_items:
    - "{{ jira_home }}/data"
    - "{{ jira_home }}/plugins"
    - "{{ jira_home }}/logos"
    - "{{ jira_home }}/import"
    - "{{ jira_home }}/export"
    - "{{ jira_home }}/caches"
  when: jira_install_datacenter

- name: Run additional actions
  become: true
  become_user: "{{ jira_user }}"
  shell: "{{ jira_install_additional_actions }}"
  when: jira_install_additional_actions|length > 0