---

- name: Add firewalld rule for jira
  ansible.posix.firewalld:
    port: "8080/tcp"
    permanent: true
    state: enabled
  notify: reload firewalld

- name: Configuring service
  systemd:
    name: "{{ jira_service_name }}"
    state: "{{ jira_service_state }}"
    enabled: "{{ jira_service_enabled }}"
    daemon_reload: yes
