---
- name: Ensure firewalld service reloaded
  systemd:
    name: firewalld
    state: reloaded
  listen: reload firewalld

- name: restart jira
  systemd:
    name: jira
    state: restarted
  when: jira_service_state != "stopped"
